- frontend/src/app/components/GenericModal.tsx
- frontend/src/app/components/Header.tsx
- frontend/src/app/components/TransactionList/TransactionItem.tsx
- frontend/src/app/components/TransactionList/TransactionModal.tsx
> improve TransactionsList & Modal

- .editorconfig
- frontend/src/app/components/Header.tsx
Features included in this PR:
- add .editorconfig for files formatting
- handle auto-reconnect wallet on page load, the connector is stored in localstorage
_Closes #18_
> feat: add .editorconfig + handle auto-reconnect wallet

- frontend/src/app/components/AddressBar.tsx
- frontend/src/app/components/ConnectModal.tsx
- frontend/src/app/components/GenericModal.tsx
- frontend/src/app/components/Header.tsx
- frontend/src/app/components/Theme.tsx
- frontend/src/app/components/TransactionList/TransactionList.tsx
- frontend/src/app/components/TransactionList/TransactionModal.tsx
- frontend/src/app/globals.css
- frontend/src/app/hooks/useTheme.ts
- frontend/src/app/layout.tsx
- frontend/src/app/page.tsx
- frontend/yarn.lock
This pull request makes the website fully responsive across all screen sizes.
Closes #{22}
> Chore: Made webpage mobile responsive (Issue#22)

- Readme.md
- package.json
> feat: Setup Devnet

- frontend/package-lock.json
- frontend/package.json
- frontend/src/app/components/CairoWikipedia/Wikipedia.tsx
- frontend/src/app/components/ui/input.tsx
- frontend/src/app/components/ui/table.tsx
- frontend/src/app/page.tsx
- frontend/src/app/wikipedia/columns.tsx
- frontend/src/app/wikipedia/data-table.tsx
- frontend/src/app/wikipedia/page.tsx
- frontend/yarn.lock
Added a table to list important resources within the ecosystem.
It is built with tanstack-table and shadcn/ui.
Features:
- Pagination controls
- Sort on name and status
- search input to filter by name
_Closes #{29}_
> Add a table with tanstack-table and shadcn/ui listing all Starknet/Cairo resources [Fixes #29]

- bin/cli.mjs
- package-lock.json
- package.json
Add the possibility of installing the project in two versions as described in #30.
Updated the CLI flow to use external library `inquirer` to make the wizard more engaging and allow for validation of the answers.
_Closes #30_
> add different types of installation

- frontend/src/app/page.tsx
> chore: sepolia faucet

- bin/cli.mjs
Disabled post-install clean up code causing installation failure, commented it out.
- [✅] I have read the [contributing docs](../CONTRIBUTING.md) (if this is your first contribution)
- [✅] This is not a duplicate of any [existing pull request](https://github.com/argentlabs/Starknet-Scaffold/pulls)
> Installation script regression fix.

- frontend/src/app/components/AddressBar.tsx
I see that stark domains are integrated into the super cool front-end template. It would be super cool to make the integration deeper by adding PFPs and domain resolving where it lacks [using Starknet React.](https://docs.starknet.id/devs/starknetreact#usestarkprofile)
Closes #38
Note: If your changes are small and straightforward, you may skip the creation of an issue beforehand and remove this section. However, for medium-to-large changes, it is recommended to have an open issue for discussion and approval prior to submitting a pull request.
> feat: adding pfp and starknames

- frontend/src/app/components/Burner/Burner.tsx
- frontend/src/app/components/BurnerWallet/BurnerWallet.tsx
- frontend/yarn.lock
Created a burner wallet UI Component
Closes #40
> feat: burner wallet component

- contracts/Scarb.toml
- contracts/scripts/lib/Scarb.toml
- contracts/scripts/lib/src/contract_script.cairo
- contracts/scripts/lib/src/lib.cairo
added deployment script for cairo contract
Closes #48
> feat: deployment script for cairo contracts

- contracts/tests/test_contract.cairo
Added a sample test contract which passes
Closes #47
> Added Sample Test

- frontend/src/app/components/AssetTransferModal.tsx
- frontend/src/app/components/Burner/Burner.tsx
- frontend/src/app/components/BurnerWallet/BurnerWallet.tsx
- frontend/src/app/utils/currency.ts
- Address the formatting eth/strk balance issue.
- Resolve the problem of the wallet array being cleared from local storage.
- Fix the error concerning max_fee when transferring funds from a burner wallet.
_Closes #67 _
> Fix issues with sending ETH/STRK using Burner wallet

- frontend/src/app/components/ScaffoldDeployer/ScaffoldDeployer.tsx
- frontend/yarn.lock
Added arguments to the deploy functionality.
Closes #65
> feat: enhanced deployer to accept arguments

- frontend/package.json
- frontend/src/app/components/AssetTransferModal.tsx
- frontend/src/app/components/BurnerWallet/BurnerWallet.tsx
- frontend/src/app/components/ContractExecutionModal.tsx
- frontend/src/app/layout.tsx
- Include estimateInvokeFee to send and execute functions 
- Include a notice reminding users to add ETH before performing transactions
- Replace window alert with toast
> feat: estimate transaction maxFee

- website/app/components/Navbar.tsx
- website/app/globals.css
Fixed the overflow issue on mobile screens
> Fixed the overflow issue on mobile screens

- docs/src/SUMMARY.md
- docs/src/chapter_2.md
- docs/src/chapter_2/subchapter_1.md
- docs/src/chapter_2/subchapter_2.md
Added a detailed documentation of Starknet-Scaffold installation and setting up of the development environment.
#82
> Quickstart installation documentation PR

- docs/src/chapter_8.md
Contributing to Starknet Scaffold.
I update the contributing docs for Starknet Scaffold for more detailed and easy understand
> I update the contributing docs more detailed and easy understand

- frontend/src/app/address-book/columns.tsx
- frontend/src/app/address-book/data-table.tsx
- frontend/src/app/address-book/page.tsx
- frontend/src/app/page.tsx
Add address book section
_Closes #83_
> chore: add address book section

- docs/src/chapter_5.md
> chore:  scripts(chapter-05) documentation

- docs/src/chapter_3/subchapter_7.md
> chore: fix Description in subchapter_7.md

- frontend/package-lock.json
- frontend/package.json
- frontend/src/app/components/AddTokenBtn.tsx
- frontend/src/app/components/Burner/Burner.tsx
- frontend/src/app/components/ui_components/AddTokenModal.tsx
- frontend/src/app/components/ui_components/Header.tsx
- frontend/yarn.lock
Implemented an AddToken button to allow users add new tokens to their wallets.
> Add token button

- frontend/src/app/page.tsx
Handled overflows in landing page cards
> feat: handled overflows in landing page cards

- frontend/src/app/components/ui_components/NetworkSwitcher.tsx
- frontend/src/app/page.tsx
> feat: network switcher drop down

- frontend/src/app/components/ui_components/NetworkSwitcher.tsx
> refac: network switcher animation

- frontend/src/app/address-book/page.tsx
- frontend/src/app/components/header/Theme.tsx
- frontend/src/app/components/ui_components/Select.tsx
- frontend/src/app/components/ui_components/pagination.tsx
- frontend/src/app/wikipedia/category-button.tsx
- frontend/src/app/wikipedia/filter.tsx
- frontend/src/app/wikipedia/page.tsx
- frontend/src/app/wikipedia/resource-card.tsx
- frontend/src/app/wikipedia/resources.tsx
- frontend/tailwind.config.ts
> chore: wiki page responsiveness

- frontend/src/app/components/AssetTransferModal.tsx
- frontend/src/app/components/ConnectionModal.tsx
- frontend/src/app/components/ContractExecutionModal.tsx
- frontend/src/app/components/ui_components/ConnectModal.tsx
> chore: fix generic modal props usage

- frontend/src/app/address-book/page.tsx
- frontend/src/app/components/header/Header.tsx
- frontend/src/app/components/header/ThemeSwitch.tsx
- frontend/src/app/components/header/UserModal.tsx
- frontend/src/app/page.tsx
- frontend/src/app/wikipedia/page.tsx
- frontend/svg/Search.tsx
> Added theme switcher to mobile

- frontend/src/app/wikipedia/resource-card.tsx
Fix resource card in wiki page
> fix: resource card in wiki page

- frontend/src/app/address-book/page.tsx
- frontend/src/app/components/TransactionList/TransactionModal.tsx
- frontend/src/app/components/header/Header.tsx
- frontend/src/app/components/header/ThemeSwitch.tsx
- frontend/src/app/components/header/UserModal.tsx
- frontend/src/app/globals.css
- frontend/src/app/wikipedia/page.tsx
- frontend/svg/Copy.tsx
> Chore add theme switcher in mobile

- scripts/install_tools.sh
Fixes sozo compatibility with dojo starter
> fix: fix sozo compatibility with dojo starter

- scripts/install_tools.sh
This PR includes Katana installation in the install script
> feat: add katana installation to install script

- frontend/src/app/burner/BurnerWallet.tsx
- frontend/src/app/burner/page.tsx
- frontend/src/app/globals.css
- frontend/src/app/layout.tsx
> Chore fix the max width of burner  wallet for tablet screens

- Website UI Design V2
- Website UI Designs and Mockup V2
**Figma File link:**
https://www.figma.com/design/GFKOuNsOVkpLtwszZaOHM4/STARKNET-SCAFFOLD?node-id=272-47&m=dev&t=qcIIBnO6wbv9K8Nx-1
**Prototype:**
https://www.figma.com/proto/GFKOuNsOVkpLtwszZaOHM4/STARKNET-SCAFFOLD?node-id=272-47&t=qcIIBnO6wbv9K8Nx-1
> Create Website UI Designs and Mockups V2

- frontend/src/app/components/lib/AddressBar.tsx
> Chore add image fallback

- frontend/src/app/components/internal/Analytics.tsx
> fix: correct hotjar_id

- .github/workflows/build_contract.yml
- .github/workflows/test_contract.yml
- bin/cli.mjs
- docs/src/chapter_5.md
- package.json
- This PR removes Kakarot support from Starknet Scaffold
- Fixes CI/CD workflows
> feat: remove kakarot support
